# Generated by Django 4.1.3 on 2022-12-23 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.CharField(default=0, max_length=1)),
                ('test_options', models.TextField(blank=True, null=True)),
                ('auto_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('button_toggle', models.CharField(blank=True, max_length=200, null=True)),
                ('checkbox', models.TextField(blank=True, null=True)),
                ('input', models.CharField(blank=True, max_length=200, null=True)),
                ('radio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.CharField(default=0, max_length=1)),
                ('checkbox', models.IntegerField(default=0)),
                ('input', models.CharField(blank=True, max_length=200, null=True)),
                ('auto_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('button_toggle', models.CharField(blank=True, max_length=200, null=True)),
                ('multi_auto_complete', models.TextField()),
                ('date_picker', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(null=True)),
                ('symbol', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
