# Generated by Django 4.1.3 on 2022-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_testcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='date_picker',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
