# Generated by Django 4.1.3 on 2022-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testmodel_date_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='multi_auto_complete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
