# Generated by Django 4.1.3 on 2023-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testmodel_multi_auto_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='multi_auto_complete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
