# Generated by Django 4.1.3 on 2023-01-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveCode',
        ),
        migrations.DeleteModel(
            name='LeaveRole',
        ),
        migrations.DeleteModel(
            name='LeaveUser',
        ),
    ]
