# Generated by Django 4.1.3 on 2023-01-26 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave', '0002_delete_leavecode_delete_leaverole_delete_leaveuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.CharField(default=0, max_length=1)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date_am', models.CharField(blank=True, max_length=1, null=True)),
                ('leave_date_pm', models.CharField(blank=True, max_length=1, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField()),
                ('attachment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.CharField(default=0, max_length=1)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_balance', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
