# Generated by Django 4.1.3 on 2023-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
