# Generated by Django 4.1.3 on 2023-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_attachment_alter_leave_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_date_am',
            new_name='leave_date_time',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_date_pm',
        ),
        migrations.AddField(
            model_name='leave',
            name='rejected_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
